[[drone]]
id = 0
connected_node_ids = [1, 5]
pdr = 0.0

[[drone]]
id = 1
connected_node_ids = [0, 2, 6]
pdr = 0.0

[[drone]]
id = 2
connected_node_ids = [1, 3, 7]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [2, 4, 8]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [3, 9]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [0, 6]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [1, 5, 7]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [2, 6, 8]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [3, 7, 9]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [4, 8]
pdr = 0.0

[[client]]
id = 10
connected_drone_ids = [0]

[[client]]
id = 11
connected_drone_ids = [5]

[[server]]
id = 12
connected_drone_ids = [4, 9]

