[[client]]
id = 0
connected_drone_ids = [3]

[[client]]
id = 1
connected_drone_ids = [8]

[[server]]
id = 2
connected_drone_ids = [7, 12]

[[drone]]
id = 3
connected_node_ids = [0, 4, 8]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [3, 5, 9]
pdr = 0.0

[[drone]]
id = 5
connected_node_ids = [4, 6, 10]
pdr = 0.0

[[drone]]
id = 6
connected_node_ids = [5, 7, 11]
pdr = 0.0

[[drone]]
id = 7
connected_node_ids = [2, 6, 12]
pdr = 0.0

[[drone]]
id = 8
connected_node_ids = [1, 3, 9]
pdr = 0.0

[[drone]]
id = 9
connected_node_ids = [4, 8, 10]
pdr = 0.0

[[drone]]
id = 10 
connected_node_ids = [5, 9, 11]
pdr = 0.0

[[drone]]
id = 11 
connected_node_ids = [6, 10, 12]
pdr = 0.0

[[drone]]
id = 12
connected_node_ids = [2, 7, 11]
pdr = 0.0

